apiVersion: v1
description: Declarative configuration for imagepullsecrets
engine: gotpl
keywords:
  - authentication
  - secrets
  - docker-registry
  - imagepullsecrets
maintainers:
  - email: ogre0403@gmail.com
    name: ogre0403
name: imagepullsecrets
version: 0.1.0
