{{- if .Values.ingress.tls.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.certificate | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}