apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpres-demo.fullname" . }}
  labels:
    app: blog
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: blog
    tier: wordpress